# Generated by Django 4.1.7 on 2023-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courseApplicationAllRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_Name", models.CharField(editable=False, max_length=100)),
                ("Course_Section", models.CharField(editable=False, max_length=100)),
                (
                    "Discussion_Time_1",
                    models.CharField(
                        choices=[
                            ("Monday 6-6:50", "Monday 6-6:50"),
                            ("Tuesday 6-6:50", "Tuesday 6-6:50"),
                            ("Wednesday 2-2:50", "Wednesday 2-2:50"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "Discussion_Time_2",
                    models.CharField(
                        choices=[
                            ("Monday 6-6:50", "Monday 6-6:50"),
                            ("Tuesday 6-6:50", "Tuesday 6-6:50"),
                            ("Wednesday 2-2:50", "Wednesday 2-2:50"),
                        ],
                        max_length=100,
                    ),
                ),
                ("First_and_Last_Name", models.CharField(max_length=100)),
                ("Username", models.CharField(blank=True, default="", max_length=100)),
                ("Resume", models.FileField(upload_to="course_app/resumes/")),
                (
                    "Anything_you_want_to_add",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "Application_Status",
                    models.CharField(default=" ", editable=False, max_length=100),
                ),
            ],
        ),
    ]
