# Generated by Django 4.1.7 on 2023-05-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_courseapplicationallrequired_discussion_time_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationallrequired',
            name='Username',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
