# Generated by Django 4.1.7 on 2023-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_courseapplicationallrequired_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationallrequired',
            name='Anything_you_want_to_add',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
