# Generated by Django 4.1.7 on 2023-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="addcoursemodel", name="Instructor",),
        migrations.AlterField(
            model_name="addcoursemodel",
            name="Discussion_Times",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="addcoursemodel",
            name="Lecture_Times",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
