# Generated by Django 4.1.7 on 2023-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_addcoursemodel_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursemodel',
            name='TA_Positions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
