# Generated by Django 4.1.5 on 2023-04-03 23:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_addcoursemodel_discussion_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursemodel',
            name='Cover_Letter',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional')], max_length=15),
        ),
        migrations.AddField(
            model_name='addcoursemodel',
            name='References',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional')], max_length=15),
        ),
        migrations.AddField(
            model_name='addcoursemodel',
            name='Resume_Required',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional')], max_length=15),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Discussion_Days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Discussion_Times',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Lecture_Days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Lecture_Times',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Marking_Meetings',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=15),
        ),
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Section',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
