# Generated by Django 4.1.5 on 2023-04-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_addcoursemodel_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursemodel',
            name='Instructor_Name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
