# Generated by Django 4.1.5 on 2023-04-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_addcoursemodel_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcoursemodel',
            name='Instructor_ID',
            field=models.CharField(max_length=10),
        ),
    ]
