# Generated by Django 4.1.5 on 2023-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_addcoursemodel_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursemodel',
            name='Status',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
