# Generated by Django 4.1.7 on 2023-04-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_addcoursemodel_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="addcoursemodel", name="Cover_Letter",),
        migrations.RemoveField(model_name="addcoursemodel", name="References",),
    ]
