# Generated by Django 4.1.7 on 2023-04-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_remove_addcoursemodel_cover_letter_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="addcoursemodel", name="Resume_Required",),
    ]
