# Generated by Django 4.1.5 on 2023-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='app_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
